# Generated by Django 6.0 on 2026-01-05 08:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, help_text='User ID from management database')),
                ('username', models.CharField(db_index=True, help_text='Username backup', max_length=150)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('VIEW', 'View')], db_index=True, max_length=10)),
                ('model_name', models.CharField(db_index=True, help_text='CRF model (e.g., SCREENINGCASE)', max_length=100)),
                ('patient_id', models.CharField(db_index=True, help_text='Patient identifier (USUBJID or SCRID)', max_length=50)),
                ('SITEID', models.CharField(blank=True, db_index=True, help_text='Site code for filtering', max_length=10, null=True)),
                ('reason', models.TextField(help_text='Combined change reason')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=40, null=True)),
                ('checksum', models.CharField(editable=False, help_text='SHA-256 checksum for integrity verification', max_length=64)),
                ('is_verified', models.BooleanField(default=True, help_text='Integrity status')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'log"."audit_log',
                'db_table_comment': 'AUDIT_LOG_TABLE',
                'ordering': ['-timestamp'],
                'default_permissions': ('add', 'view'),
                'indexes': [models.Index(fields=['-timestamp'], name='audit_log_time_idx'), models.Index(fields=['patient_id', '-timestamp'], name='audit_log_patient_idx'), models.Index(fields=['user_id', '-timestamp'], name='audit_log_user_idx'), models.Index(fields=['SITEID', '-timestamp'], name='audit_log_site_idx'), models.Index(fields=['model_name', 'action'], name='audit_log_model_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLogDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Technical field name', max_length=100)),
                ('old_value', models.TextField(blank=True, help_text='Old value (as string)', null=True)),
                ('new_value', models.TextField(blank=True, help_text='New value (as string)', null=True)),
                ('reason', models.TextField(help_text='Reason for this specific field change')),
                ('audit_log', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='audit_log.auditlog')),
            ],
            options={
                'verbose_name': 'Audit Log Detail',
                'verbose_name_plural': 'Audit Log Details',
                'db_table': 'log"."audit_log_detail',
                'db_table_comment': 'AUDIT_LOG_TABLE',
                'ordering': ['field_name'],
                'default_permissions': ('add', 'view'),
                'indexes': [models.Index(fields=['audit_log', 'field_name'], name='audit_detail_log_idx')],
            },
        ),
    ]
