# Generated by Django 5.2.4 on 2025-08-28 04:01

import django.core.validators
import django.db.models.deletion
import parler.fields
import parler.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Study",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique code for the study (e.g., STUDY001).",
                        max_length=50,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "db_name",
                    models.CharField(
                        db_index=True,
                        help_text="Name of the database for this study (e.g., db_study_001).",
                        max_length=100,
                        unique=True,
                        verbose_name="Database Name",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        help_text="Current status of the study (active, inactive, archived).",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
            ],
            options={
                "verbose_name": "Study",
                "verbose_name_plural": "Study Information",
                "db_table": "study_information",
                "ordering": ("code",),
                "abstract": False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique code for the permission (e.g., manage_db).",
                        max_length=50,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the permission (e.g., Manage Database).",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the permission.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
                "db_table": "study_permissions",
                "ordering": ("code",),
                "indexes": [models.Index(fields=["name"], name="ix_perm_name")],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Za-z0-9\\s\\-]+$"
                            )
                        ],
                        verbose_name="Title",
                    ),
                ),
                (
                    "responsibilities",
                    models.TextField(
                        help_text="Description of the role's responsibilities.",
                        verbose_name="Responsibilities",
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        db_index=True,
                        max_length=5,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator("^[A-Z]{2,5}$")
                        ],
                        verbose_name="Abbreviation",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles in Study",
                "db_table": "study_roles",
                "ordering": ("title",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("abbreviation__regex", "^[A-Z]{2,5}$")),
                        name="roles_abbreviation_check",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique global code for the site (e.g., SITE01).",
                        max_length=50,
                        unique=True,
                        verbose_name="Site Code",
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        db_index=True,
                        help_text="Short abbreviation for the site (e.g., S01).",
                        max_length=10,
                        unique=True,
                        verbose_name="Abbreviation",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
            ],
            options={
                "verbose_name": "Study Site",
                "verbose_name_plural": "Study Sites",
                "db_table": "study_sites",
                "ordering": ("code",),
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("abbreviation__regex", "^[A-Z0-9]{2,10}$")),
                        name="site_abbreviation_check",
                    )
                ],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="StudySite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_sites",
                        to="tenancy.site",
                        verbose_name="Site",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_sites",
                        to="tenancy.study",
                        verbose_name="Study",
                    ),
                ),
            ],
            options={
                "verbose_name": "Study-Site Link",
                "verbose_name_plural": "Study-Site Links",
                "db_table": "study_site_links",
            },
        ),
        migrations.CreateModel(
            name="StudyMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Assigned At"),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="study_memberships",
                        to="tenancy.role",
                        verbose_name="Role",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="tenancy.study",
                        verbose_name="Study",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "study_site",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional site within the study; null for study-level access.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="tenancy.studysite",
                        verbose_name="Study Site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Study Membership",
                "verbose_name_plural": "Study Memberships",
                "db_table": "study_membership",
            },
        ),
        migrations.AddField(
            model_name="study",
            name="sites",
            field=models.ManyToManyField(
                related_name="studies",
                through="tenancy.StudySite",
                to="tenancy.site",
                verbose_name="Sites",
            ),
        ),
        migrations.CreateModel(
            name="StudyTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Name of the study.",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "introduction",
                    models.TextField(
                        blank=True,
                        help_text="Brief introduction or description of the study.",
                        null=True,
                        verbose_name="Introduction",
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="tenancy.study",
                    ),
                ),
            ],
            options={
                "verbose_name": "Study Translation",
                "db_table": "study_information_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="tenancy.permission",
                        verbose_name="Permission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="tenancy.role",
                        verbose_name="Role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Permission",
                "verbose_name_plural": "Role Permissions",
                "db_table": "study_role_permissions",
                "indexes": [
                    models.Index(fields=["role"], name="ix_roleperm_role"),
                    models.Index(fields=["permission"], name="ix_roleperm_perm"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("role", "permission"), name="uq_role_permission"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SiteTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the site.",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="tenancy.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Study Site Translation",
                "db_table": "study_sites_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name="studysite",
            index=models.Index(fields=["study"], name="ix_studysite_study"),
        ),
        migrations.AddIndex(
            model_name="studysite",
            index=models.Index(fields=["site"], name="ix_studysite_site"),
        ),
        migrations.AddConstraint(
            model_name="studysite",
            constraint=models.UniqueConstraint(
                fields=("study", "site"), name="uq_study_site"
            ),
        ),
        migrations.AddIndex(
            model_name="studymembership",
            index=models.Index(fields=["user"], name="ix_membership_user"),
        ),
        migrations.AddIndex(
            model_name="studymembership",
            index=models.Index(fields=["study"], name="ix_membership_study"),
        ),
        migrations.AddIndex(
            model_name="studymembership",
            index=models.Index(fields=["study_site"], name="ix_membership_site"),
        ),
        migrations.AddIndex(
            model_name="studymembership",
            index=models.Index(fields=["role"], name="ix_membership_role"),
        ),
        migrations.AddIndex(
            model_name="studymembership",
            index=models.Index(
                fields=["user", "study"], name="ix_membership_user_study"
            ),
        ),
        migrations.AddConstraint(
            model_name="studymembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("study_site__isnull", False)),
                fields=("user", "study", "study_site", "role"),
                name="uq_user_study_site_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="studymembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("study_site__isnull", True)),
                fields=("user", "study", "role"),
                name="uq_user_study_role",
            ),
        ),
        migrations.AddIndex(
            model_name="study",
            index=models.Index(fields=["status", "code"], name="ix_study_status_code"),
        ),
        migrations.AddConstraint(
            model_name="study",
            constraint=models.CheckConstraint(
                condition=models.Q(("db_name__istartswith", "db_study_")),
                name="db_name_prefix_check",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studytranslation",
            unique_together={("language_code", "master")},
        ),
    ]
