# Generated by Django 5.2.4 on 2025-08-14 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Study",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique code for the study (e.g., STUDY001).",
                        max_length=50,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Name of the study.",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "introduction",
                    models.TextField(
                        blank=True,
                        help_text="Brief introduction or description of the study.",
                        null=True,
                        verbose_name="Introduction",
                    ),
                ),
                (
                    "db_name",
                    models.CharField(
                        db_index=True,
                        help_text="Name of the database for this study (e.g., db_study_001).",
                        max_length=100,
                        unique=True,
                        verbose_name="Database Name",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        help_text="Current status of the study (active, inactive, archived).",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Study",
                "verbose_name_plural": "Studies",
                "db_table": "study_infomation",
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="StudyMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Assigned At"),
                ),
            ],
            options={
                "verbose_name": "Study Membership",
                "verbose_name_plural": "Study Memberships",
                "db_table": "study_membership",
            },
        ),
        migrations.CreateModel(
            name="StudyTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True,
                        help_text="Language code for the translation (e.g., vi, en, en-US).",
                        max_length=16,
                        verbose_name="Language Code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Translated name of the study.",
                        max_length=255,
                        verbose_name="Translated Name",
                    ),
                ),
                (
                    "introduction",
                    models.TextField(
                        blank=True,
                        help_text="Translated introduction of the study.",
                        null=True,
                        verbose_name="Translated Introduction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Study Translation",
                "verbose_name_plural": "Study Translations",
                "db_table": "study_translations",
                "ordering": ("study_id", "language_code"),
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique code for the permission (e.g., manage_db).",
                        max_length=50,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name of the permission (e.g., Manage Database).",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the permission.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
                "db_table": "study_permissions",
                "ordering": ("code",),
                "indexes": [models.Index(fields=["name"], name="ix_perm_name")],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True,
                        help_text="Unique title for the role (e.g., Database Administrator).",
                        max_length=100,
                        unique=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "responsibilities",
                    models.TextField(
                        help_text="Description of the role's responsibilities.",
                        verbose_name="Responsibilities",
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        db_index=True,
                        help_text="Short code for the role (2-5 uppercase letters, e.g., DBA).",
                        max_length=5,
                        unique=True,
                        verbose_name="Abbreviation",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "db_table": "study_roles",
                "ordering": ("title",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("abbreviation__regex", "^[A-Z]{2,5}$")),
                        name="roles_abbreviation_check",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="tenancy.permission",
                        verbose_name="Permission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="tenancy.role",
                        verbose_name="Role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Permission",
                "verbose_name_plural": "Role Permissions",
                "db_table": "study_role_permissions",
            },
        ),
        migrations.CreateModel(
            name="StudyConfig",
            fields=[
                (
                    "study",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="config",
                        serialize=False,
                        to="tenancy.study",
                        verbose_name="Study",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict,
                        help_text="JSON configuration for the study (e.g., custom settings).",
                        verbose_name="Configuration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Study Configuration",
                "verbose_name_plural": "Study Configurations",
                "db_table": "study_configs",
            },
        ),
        migrations.AddIndex(
            model_name="study",
            index=models.Index(fields=["status", "code"], name="ix_study_status_code"),
        ),
        migrations.AddConstraint(
            model_name="study",
            constraint=models.CheckConstraint(
                condition=models.Q(("db_name__regex", "^[A-Za-z0-9_]+$")),
                name="valid_db_name",
            ),
        ),
        migrations.AddField(
            model_name="studymembership",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="study_memberships",
                to="tenancy.role",
                verbose_name="Role",
            ),
        ),
        migrations.AddField(
            model_name="studymembership",
            name="study",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="tenancy.study",
                verbose_name="Study",
            ),
        ),
        migrations.AddField(
            model_name="studymembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="study_memberships",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="studytranslation",
            name="study",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="tenancy.study",
                verbose_name="Study",
            ),
        ),
        migrations.AddIndex(
            model_name="rolepermission",
            index=models.Index(fields=["role"], name="ix_roleperm_role"),
        ),
        migrations.AddIndex(
            model_name="rolepermission",
            index=models.Index(fields=["permission"], name="ix_roleperm_perm"),
        ),
        migrations.AddConstraint(
            model_name="rolepermission",
            constraint=models.UniqueConstraint(
                fields=("role", "permission"), name="uq_role_permission"
            ),
        ),
        migrations.AddIndex(
            model_name="studymembership",
            index=models.Index(fields=["user"], name="ix_membership_user"),
        ),
        migrations.AddIndex(
            model_name="studymembership",
            index=models.Index(fields=["study"], name="ix_membership_study"),
        ),
        migrations.AddIndex(
            model_name="studymembership",
            index=models.Index(fields=["role"], name="ix_membership_role"),
        ),
        migrations.AddIndex(
            model_name="studymembership",
            index=models.Index(
                fields=["user", "study"], name="ix_membership_user_study"
            ),
        ),
        migrations.AddConstraint(
            model_name="studymembership",
            constraint=models.UniqueConstraint(
                fields=("user", "study", "role"), name="uq_user_study_role"
            ),
        ),
        migrations.AddIndex(
            model_name="studytranslation",
            index=models.Index(fields=["study", "language_code"], name="ix_study_lang"),
        ),
        migrations.AddConstraint(
            model_name="studytranslation",
            constraint=models.UniqueConstraint(
                fields=("study", "language_code"), name="uq_study_lang"
            ),
        ),
        migrations.AddConstraint(
            model_name="studytranslation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("language_code__regex", "^[A-Za-z]{2,3}([-_][A-Za-z0-9]+)*$")
                ),
                name="valid_language_code",
            ),
        ),
    ]
