# Generated by Django 5.2 on 2025-08-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studymembership',
            options={'ordering': ['-assigned_at'], 'verbose_name': 'Study Membership', 'verbose_name_plural': 'Study Memberships'},
        ),
        migrations.RemoveConstraint(
            model_name='study',
            name='valid_db_name',
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('code', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('title', 'abbreviation')},
        ),
        migrations.AddConstraint(
            model_name='study',
            constraint=models.CheckConstraint(condition=models.Q(('db_name__istartswith', 'db_study_')), name='db_name_prefix_check'),
        ),
    ]
