# Generated by Django 4.2.20 on 2025-07-31 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_43en', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialantibiotic',
            name='USUBJID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial_antibiotics', to='study_43en.screeningcase', to_field='USUBJID'),
        ),
        migrations.AlterField(
            model_name='laboratorytest',
            name='clinical_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='study_43en.screeningcase', to_field='USUBJID'),
        ),
        migrations.AlterField(
            model_name='mainantibiotic',
            name='USUBJID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_antibiotics', to='study_43en.screeningcase', to_field='USUBJID'),
        ),
        migrations.AlterField(
            model_name='microbiologyculture',
            name='clinical_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microbiology_cultures', to='study_43en.screeningcase', to_field='USUBJID'),
        ),
        migrations.AlterField(
            model_name='priorantibiotic',
            name='USUBJID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prior_antibiotics', to='study_43en.screeningcase', to_field='USUBJID'),
        ),
        migrations.AlterField(
            model_name='samplecollection',
            name='clinical_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_collections', to='study_43en.screeningcase', to_field='USUBJID'),
        ),
        migrations.AlterField(
            model_name='vasoidrug',
            name='USUBJID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaso_drugs', to='study_43en.screeningcase', to_field='USUBJID'),
        ),
    ]
