# Generated by Django 4.2.20 on 2025-08-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_43en', '0002_alter_initialantibiotic_usubjid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screeningcase',
            options={},
        ),
        migrations.AlterField(
            model_name='screeningcase',
            name='SUBJID',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Subject ID'),
        ),
        migrations.AlterModelTable(
            name='screeningcase',
            table=None,
        ),
    ]
