# Generated by Django 4.2.20 on 2025-08-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_43en', '0003_alter_screeningcase_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningcase',
            name='UNRECRUITED_REASON',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lý do không tuyển'),
        ),
        migrations.AddField(
            model_name='screeningcase',
            name='WARD',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Khoa/Phòng'),
        ),
    ]
