# Generated by Django 4.2.20 on 2025-08-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_43en', '0004_screeningcase_unrecruited_reason_screeningcase_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningcontact',
            name='WARD',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Khoa/Phòng'),
        ),
    ]
