# Generated by Django 4.2.20 on 2025-08-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_43en', '0005_screeningcontact_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningcontact',
            name='UNRECRUITED_REASON',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lý do không tuyển'),
        ),
    ]
