# Generated by Django 4.2.20 on 2025-08-04 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_43en', '0006_screeningcontact_unrecruited_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(blank=True, null=True, verbose_name='Ngày tham gia nghiên cứu')),
                ('d10_start_date', models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu khoảng D10')),
                ('d10_end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc khoảng D10')),
                ('d10_expected_date', models.DateField(blank=True, null=True, verbose_name='Ngày dự kiến D10')),
                ('d28_start_date', models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu khoảng D28')),
                ('d28_end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc khoảng D28')),
                ('d28_expected_date', models.DateField(blank=True, null=True, verbose_name='Ngày dự kiến D28')),
                ('d90_start_date', models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu khoảng D90')),
                ('d90_end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc khoảng D90')),
                ('d90_expected_date', models.DateField(blank=True, null=True, verbose_name='Ngày dự kiến D90')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expected_dates', to='study_43en.enrollmentcase', verbose_name='Bệnh nhân')),
            ],
            options={
                'verbose_name': 'Ngày dự kiến',
                'verbose_name_plural': 'Ngày dự kiến',
                'db_table': 'study_43en_expecteddates',
            },
        ),
    ]
