# Generated by Django 4.2.24 on 2025-12-19 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_44en', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individual_followup',
            old_name='id',
            new_name='FOLLOW_UP_id',
        ),
    ]
