# Generated by Django 5.2.9 on 2025-12-22 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_44en', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual_comorbidity',
            name='MEMBER',
            field=models.ForeignKey(db_column='MEMBERID', on_delete=django.db.models.deletion.CASCADE, related_name='comorbidities', to='study_44en.individual_exposure'),
        ),
        migrations.AlterField(
            model_name='individual_hospitalization',
            name='MEMBER',
            field=models.ForeignKey(db_column='MEMBERID', on_delete=django.db.models.deletion.CASCADE, related_name='hospitalizations', to='study_44en.individual_exposure'),
        ),
        migrations.AlterField(
            model_name='individual_medication',
            name='MEMBER',
            field=models.ForeignKey(db_column='MEMBERID', on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='study_44en.individual_exposure'),
        ),
        migrations.AlterField(
            model_name='individual_sample',
            name='MEMBER',
            field=models.ForeignKey(db_column='MEMBERID', on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='study_44en.individual'),
        ),
        migrations.AlterField(
            model_name='individual_symptom',
            name='FOLLOW_UP',
            field=models.ForeignKey(db_column='FUID', on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='study_44en.individual_followup'),
        ),
        migrations.AlterField(
            model_name='individual_travel',
            name='MEMBER',
            field=models.ForeignKey(db_column='MEMBERID', on_delete=django.db.models.deletion.CASCADE, related_name='travel_history', to='study_44en.individual'),
        ),
        migrations.AlterField(
            model_name='individual_vaccine',
            name='MEMBER',
            field=models.ForeignKey(db_column='MEMBERID', on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='study_44en.individual_exposure'),
        ),
        migrations.AlterField(
            model_name='individual_watersource',
            name='MEMBER',
            field=models.ForeignKey(db_column='MEMBERID', on_delete=django.db.models.deletion.CASCADE, related_name='water_sources', to='study_44en.individual_exposure'),
        ),
        migrations.AlterField(
            model_name='individual_watertreatment',
            name='MEMBER',
            field=models.ForeignKey(db_column='MEMBERID', on_delete=django.db.models.deletion.CASCADE, related_name='treatment_methods', to='study_44en.individual_exposure'),
        ),
        migrations.AlterModelTable(
            name='individual_symptom',
            table='FollowUp_Symptom',
        ),
        migrations.CreateModel(
            name='FollowUp_Hospitalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0, editable=False, help_text='Version number for optimistic locking')),
                ('last_modified_by_id', models.IntegerField(blank=True, db_index=True, editable=False, help_text='User ID who last modified this record', null=True)),
                ('last_modified_by_username', models.CharField(blank=True, db_index=True, editable=False, help_text='Username backup for audit trail', max_length=150, null=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp of last modification')),
                ('HOSPITAL_TYPE', models.CharField(choices=[('central', 'Bệnh viện trung ương'), ('city', 'Bệnh viện thành phố'), ('district', 'Bệnh viện quận, huyện'), ('private', 'Bệnh viện tư'), ('other', 'Other')], db_index=True, max_length=20)),
                ('HOSPITAL_OTHER', models.CharField(blank=True, max_length=200, null=True)),
                ('DURATION', models.CharField(blank=True, choices=[('1-3', '1-3 ngày'), ('3-5', '3-5 ngày'), ('5-7', '5-7 ngày'), ('>7', 'Trên 7 ngày')], max_length=10, null=True)),
                ('FOLLOW_UP', models.ForeignKey(db_column='FUID', on_delete=django.db.models.deletion.CASCADE, related_name='hospitalizations', to='study_44en.individual_followup')),
            ],
            options={
                'verbose_name': 'Follow-up Hospitalization',
                'verbose_name_plural': 'Follow-up Hospitalizations',
                'db_table': 'FollowUp_Hospitalization',
                'ordering': ['FOLLOW_UP', 'HOSPITAL_TYPE'],
                'unique_together': {('FOLLOW_UP', 'HOSPITAL_TYPE')},
            },
        ),
        migrations.DeleteModel(
            name='Individual_FollowUp_Hospitalization',
        ),
    ]
