# Generated by Django 5.2.10 on 2026-01-15 03:54

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_44en', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hh_personal_data',
            name='HOUSE_NUMBER',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, help_text='House number, building name, apartment, etc. (encrypted)', max_length=255, null=True, verbose_name='House Number/Building Details'),
        ),
        migrations.AlterField(
            model_name='hh_personal_data',
            name='STREET',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Street or road name (encrypted)', max_length=255, null=True, verbose_name='Street/Road Name'),
        ),
    ]
