# Generated by Django 5.2.9 on 2025-12-22 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_44en', '0002_alter_individual_comorbidity_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual_followup',
            name='MEMBER',
            field=models.ForeignKey(db_column='MEMBERID', on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='study_44en.individual'),
        ),
    ]
