# Generated by Django 5.1.4 on 2025-12-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_44en', '0003_alter_individual_followup_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hh_member',
            name='MEMBERID',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, verbose_name='Member ID'),
        ),
        migrations.AlterField(
            model_name='individual_exposure',
            name='MEDICATION_3M',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', "Don't know")], max_length=20, null=True, verbose_name='Used Medication (3 months)'),
        ),
    ]
