# Generated by Django 6.0 on 2026-01-02 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_44en', '0004_alter_hh_member_memberid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individual_comorbidity',
            options={'ordering': ['MEMBERID', 'COMORBIDITY_TYPE'], 'verbose_name': 'Comorbidity', 'verbose_name_plural': 'Comorbidities'},
        ),
        migrations.AlterModelOptions(
            name='individual_followup',
            options={'ordering': ['MEMBERID', 'VISIT_TIME'], 'verbose_name': 'Follow-up Visit', 'verbose_name_plural': 'Follow-up Visits'},
        ),
        migrations.AlterModelOptions(
            name='individual_hospitalization',
            options={'ordering': ['MEMBERID', 'HOSPITAL_TYPE'], 'verbose_name': 'Hospitalization', 'verbose_name_plural': 'Hospitalizations'},
        ),
        migrations.AlterModelOptions(
            name='individual_medication',
            options={'ordering': ['MEMBERID', 'MEDICATION_TYPE'], 'verbose_name': 'Medication', 'verbose_name_plural': 'Medications'},
        ),
        migrations.AlterModelOptions(
            name='individual_sample',
            options={'ordering': ['MEMBERID', 'SAMPLE_TIME'], 'verbose_name': 'Sample Collection', 'verbose_name_plural': 'Sample Collections'},
        ),
        migrations.AlterModelOptions(
            name='individual_travel',
            options={'ordering': ['MEMBERID', 'TRAVEL_TYPE'], 'verbose_name': 'Travel History', 'verbose_name_plural': 'Travel Histories'},
        ),
        migrations.AlterModelOptions(
            name='individual_vaccine',
            options={'ordering': ['MEMBERID', 'VACCINE_TYPE'], 'verbose_name': 'Vaccine', 'verbose_name_plural': 'Vaccines'},
        ),
        migrations.AlterModelOptions(
            name='individual_watersource',
            options={'ordering': ['MEMBERID', 'SOURCE_TYPE'], 'verbose_name': 'Individual Water Source', 'verbose_name_plural': 'Individual Water Sources'},
        ),
        migrations.AlterModelOptions(
            name='individual_watertreatment',
            options={'ordering': ['MEMBERID', 'TREATMENT_TYPE'], 'verbose_name': 'Individual Water Treatment', 'verbose_name_plural': 'Individual Water Treatments'},
        ),
        migrations.RenameField(
            model_name='individual',
            old_name='MEMBER',
            new_name='MEMBERID',
        ),
        migrations.RenameField(
            model_name='individual_comorbidity',
            old_name='MEMBER',
            new_name='MEMBERID',
        ),
        migrations.RenameField(
            model_name='individual_exposure',
            old_name='MEMBER',
            new_name='MEMBERID',
        ),
        migrations.RenameField(
            model_name='individual_followup',
            old_name='MEMBER',
            new_name='MEMBERID',
        ),
        migrations.RenameField(
            model_name='individual_foodfrequency',
            old_name='MEMBER',
            new_name='MEMBERID',
        ),
        migrations.RenameField(
            model_name='individual_hospitalization',
            old_name='MEMBER',
            new_name='MEMBERID',
        ),
        migrations.RenameField(
            model_name='individual_medication',
            old_name='MEMBER',
            new_name='MEMBERID',
        ),
        migrations.RenameField(
            model_name='individual_sample',
            old_name='MEMBER',
            new_name='MEMBERID',
        ),
        migrations.RenameField(
            model_name='individual_travel',
            old_name='MEMBER',
            new_name='MEMBERID',
        ),
        migrations.RenameField(
            model_name='individual_vaccine',
            old_name='MEMBER',
            new_name='MEMBERID',
        ),
        migrations.RenameField(
            model_name='individual_watersource',
            old_name='MEMBER',
            new_name='MEMBERID',
        ),
        migrations.RenameField(
            model_name='individual_watertreatment',
            old_name='MEMBER',
            new_name='MEMBERID',
        ),
        migrations.AlterUniqueTogether(
            name='individual_comorbidity',
            unique_together={('MEMBERID', 'COMORBIDITY_TYPE')},
        ),
        migrations.AlterUniqueTogether(
            name='individual_sample',
            unique_together={('MEMBERID', 'SAMPLE_TIME')},
        ),
        migrations.AlterUniqueTogether(
            name='individual_travel',
            unique_together={('MEMBERID', 'TRAVEL_TYPE')},
        ),
        migrations.AlterUniqueTogether(
            name='individual_vaccine',
            unique_together={('MEMBERID', 'VACCINE_TYPE')},
        ),
        migrations.AlterUniqueTogether(
            name='individual_watersource',
            unique_together={('MEMBERID', 'SOURCE_TYPE')},
        ),
        migrations.AlterUniqueTogether(
            name='individual_watertreatment',
            unique_together={('MEMBERID', 'TREATMENT_TYPE')},
        ),
    ]
