# Generated by Django 6.0 on 2026-01-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_44en', '0005_alter_individual_comorbidity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='SUBJECTID',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Auto-populated from MEMBERID. Format: 44EN-001-1', max_length=50, null=True, unique=True, verbose_name='Subject ID'),
        ),
        migrations.AddIndex(
            model_name='individual',
            index=models.Index(fields=['SUBJECTID'], name='idx_individual_subjectid'),
        ),
    ]
