# Generated by Django 6.0 on 2026-01-08 09:36

import django.db.models.deletion
import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_44en', '0006_individual_subjectid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HH_PERSONAL_DATA',
            fields=[
                ('version', models.IntegerField(default=0, editable=False, help_text='Version number for optimistic locking')),
                ('last_modified_by_id', models.IntegerField(blank=True, db_index=True, editable=False, help_text='User ID who last modified this record', null=True)),
                ('last_modified_by_username', models.CharField(blank=True, db_index=True, editable=False, help_text='Username backup for audit trail', max_length=150, null=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp of last modification')),
                ('HHID', models.OneToOneField(db_column='HHID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='personal_data', serialize=False, to='study_44en.hh_case', verbose_name='Household ID')),
                ('STREET', encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Street address (encrypted)', max_length=255, null=True, verbose_name='Street/Road/Block')),
                ('WARD', encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Ward or commune (encrypted)', max_length=255, null=True, verbose_name='Ward/Commune')),
                ('CITY', encrypted_fields.fields.EncryptedCharField(blank=True, help_text='City (encrypted)', max_length=255, null=True, verbose_name='City')),
            ],
            options={
                'verbose_name': 'Household Personal Data',
                'verbose_name_plural': 'Household Personal Data',
                'db_table': 'HH_PERSONAL_DATA',
            },
        ),
        migrations.RemoveIndex(
            model_name='hh_case',
            name='idx_hh_location',
        ),
        migrations.AddIndex(
            model_name='hh_personal_data',
            index=models.Index(fields=['last_modified_by_id', '-last_modified_at'], name='idx_hhpdata_modified'),
        ),
        migrations.RemoveField(
            model_name='hh_case',
            name='CITY',
        ),
        migrations.RemoveField(
            model_name='hh_case',
            name='STREET',
        ),
        migrations.RemoveField(
            model_name='hh_case',
            name='WARD',
        ),
    ]
