"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-ixjr^!h4-kmbvx7lfo4c=@%@0bd0p1$$#)5i5+xa*6c_gchlh6"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_bootstrap5',
    #'study_43en.apps.Study43enConfig',
    'chartjs',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware', 
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            #os.path.join(BASE_DIR, 'templates'),  # Thư mục templates chính
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                #'study_43en.context_processors.upcoming_appointments',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Multiple Databases Configuration
DATABASES = {
    # Database cho Django admin, auth, sessions, contenttypes
    'default': {
        # 'ENGINE': 'django.db.backends.postgresql',
        # 'NAME': 'admin_system',
        # 'USER': 'postgres',  # 🔄 Thay bằng username PostgreSQL của bạn
        # 'PASSWORD': 'duyduy123',  # 🔄 Thay bằng password PostgreSQL của bạn
        # 'HOST': 'localhost',
        # 'PORT': '5432',
        # # Bỏ OPTIONS charset cho PostgreSQL
        # 'TEST': {
        #     'NAME': 'test_admin_system',
        # }
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    },
    
    # # Database có sẵn cho app fourtythree
    # 'fourtythree_db': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'fourtythree_db',  # Database đã có sẵn
    #     'USER': 'postgres',  # 🔄 Thay bằng username PostgreSQL của bạn
    #     'PASSWORD': 'duyduy123',  # 🔄 Thay bằng password PostgreSQL của bạn
    #     'HOST': 'localhost',
    #     'PORT': '5432',
    #     # Bỏ OPTIONS charset cho PostgreSQL
    #     'TEST': {
    #         'NAME': 'test_fourtythree_db',
    #     }
    # }
}

# Database routing
#DATABASE_ROUTERS = ['study_data_management.db_router.DatabaseRouter']

# Mapping apps to databases
# DATABASE_APPS_MAPPING = {
#     'study_43en': 'fourtythree_db',
#     'admin': 'default',
#     'auth': 'default',
#     'contenttypes': 'default',
#     'sessions': 'default',
# }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'vi'  # Ngôn ngữ mặc định là tiếng Việt

# Danh sách các ngôn ngữ được hỗ trợ
LANGUAGES = [
    ('vi', 'Vietnamese'),  # Tiếng Việt
    ('en', 'English'),     # Tiếng Anh
]

# Đường dẫn để lưu các file dịch (translation files)
LOCALE_PATHS = [
    BASE_DIR / 'locale',  # Thư mục locale sẽ chứa các file dịch
]

# Kích hoạt i18n
USE_I18N = True

# Kích hoạt l10n (localization) để hỗ trợ định dạng ngày giờ, số, v.v.
USE_L10N = True

# Thiết lập múi giờ
TIME_ZONE = 'Asia/Ho_Chi_Minh'  # Múi giờ Việt Nam (GMT+7)

# Bật hỗ trợ múi giờ
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'  # Tên URL đăng nhập, khớp với path('login/', ...)
LOGIN_REDIRECT_URL = 'select_study'
LOGOUT_REDIRECT_URL = 'login'

# Cấu hình gửi email qua Gmail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'nhoxduy12345x@gmail.com'  # Thay bằng email của bạn
EMAIL_HOST_PASSWORD = 'kvze kvmq ilhv leoj'  # Thay bằng mật khẩu ứng dụng của Gmail
DEFAULT_FROM_EMAIL = 'nhoxduy12345x@gmail.com'  # Email gửi mặc định


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        # Thêm logger cho __name__ nếu cần
        '__main__': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}