# Generated by Django 5.2.6 on 2025-10-12 04:16

import backends.tenancy.models.user
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import parler.fields
import parler.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('last_study_accessed_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Study Access Time')),
                ('must_change_password', models.BooleanField(default=False, verbose_name='Must Change Password')),
                ('password_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='Password Changed At')),
                ('failed_login_attempts', models.IntegerField(default=0, verbose_name='Failed Login Attempts')),
                ('last_failed_login', models.DateTimeField(blank=True, null=True, verbose_name='Last Failed Login')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about user account status or issues', verbose_name='Admin Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, help_text='The admin/staff user who created this account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By (Admin User)')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Authentication Users',
                'verbose_name_plural': 'Authentication Users',
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', backends.tenancy.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Code must contain only uppercase letters, numbers, and underscores', regex='^[A-Z0-9_]+$')], verbose_name='Site Code')),
                ('abbreviation', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Abbreviation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Study Sites',
                'verbose_name_plural': 'Study Sites',
                'db_table': 'study_sites',
                'ordering': ['code'],
                'abstract': False,
                'indexes': [models.Index(fields=['code'], name='idx_site_code')],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Unique code for the study (e.g., 43EN, 44EN) - uppercase letters, numbers, underscores only', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Code must contain only uppercase letters, numbers, and underscores', regex='^[A-Z0-9_]+$')], verbose_name='Study Code')),
                ('db_name', models.CharField(blank=True, db_index=True, help_text='Auto-generated from study code (e.g., db_study_43en). Leave blank for auto-generation.', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message="Database name must start with 'db_study_' and contain only lowercase letters, numbers, and underscores", regex='^db_study_[a-z0-9_]+$')], verbose_name='Database Name')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('archived', 'Archived')], db_index=True, default='planning', help_text="Study status. Archived studies won't be loaded by the system.", max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studies_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Study Information',
                'verbose_name_plural': 'Study Information',
                'db_table': 'study_information',
                'ordering': ['-created_at', 'code'],
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='user',
            name='last_study_accessed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_accessed_by', to='tenancy.study', verbose_name='Last Study Accessed'),
        ),
        migrations.CreateModel(
            name='StudySite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_studies', to='tenancy.site', verbose_name='Site')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sites', to='tenancy.study', verbose_name='Study')),
            ],
            options={
                'verbose_name': 'Study-Site Link',
                'verbose_name_plural': 'Study-Site Links',
                'db_table': 'study_site_links',
            },
        ),
        migrations.CreateModel(
            name='StudyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('can_access_all_sites', models.BooleanField(default=False, help_text='If true, user has access to all sites in the study', verbose_name='Can Access All Sites')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this membership', verbose_name='Notes')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Assigned At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By')),
                ('group', models.ForeignKey(help_text='Select a role for this study. User will be automatically added to this group.', on_delete=django.db.models.deletion.PROTECT, related_name='study_memberships', to='auth.group', verbose_name='Role (Group)')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenancy.study', verbose_name='Study')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_memberships', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('study_sites', models.ManyToManyField(blank=True, help_text='Specific sites within the study. Leave empty for all sites.', related_name='memberships', to='tenancy.studysite', verbose_name='Study Sites')),
            ],
            options={
                'verbose_name': 'Study Membership',
                'verbose_name_plural': 'Study Memberships',
                'db_table': '"management"."study_memberships"',
            },
        ),
        migrations.AddField(
            model_name='study',
            name='sites',
            field=models.ManyToManyField(related_name='studies', through='tenancy.StudySite', to='tenancy.site', verbose_name='Sites'),
        ),
        migrations.CreateModel(
            name='StudyTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.TextField(db_index=True, max_length=255, verbose_name='Study Name')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tenancy.study')),
            ],
            options={
                'verbose_name': 'Study Information Translation',
                'db_table': 'study_information_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SiteTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.TextField(max_length=255, verbose_name='Name')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tenancy.site')),
            ],
            options={
                'verbose_name': 'Study Sites Translation',
                'db_table': 'study_sites_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='idx_user_username'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='idx_user_email'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='idx_user_is_active'),
        ),
        migrations.AddIndex(
            model_name='studysite',
            index=models.Index(fields=['study'], name='idx_studysite'),
        ),
        migrations.AddIndex(
            model_name='studysite',
            index=models.Index(fields=['site'], name='ix_studysite_site'),
        ),
        migrations.AddConstraint(
            model_name='studysite',
            constraint=models.UniqueConstraint(fields=('study', 'site'), name='unique_study_site'),
        ),
        migrations.AddIndex(
            model_name='studymembership',
            index=models.Index(fields=['user', 'study', 'is_active'], name='idx_membership_user_study'),
        ),
        migrations.AddIndex(
            model_name='studymembership',
            index=models.Index(fields=['study', 'is_active'], name='idx_membership_study'),
        ),
        migrations.AddIndex(
            model_name='studymembership',
            index=models.Index(fields=['group'], name='idx_membership_group'),
        ),
        migrations.AddConstraint(
            model_name='studymembership',
            constraint=models.UniqueConstraint(fields=('user', 'study'), name='unique_user_study'),
        ),
        migrations.AddIndex(
            model_name='study',
            index=models.Index(fields=['status', 'code'], name='idx_study_status_code'),
        ),
        migrations.AlterUniqueTogether(
            name='studytranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
