# Generated by Django 5.2.8 on 2025-12-16 09:46

import backends.tenancy.models.user
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('must_change_password', models.BooleanField(default=True, help_text='User must change password on next login')),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('last_study_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('last_study_accessed_id', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_created', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Authentication Users',
                'verbose_name_plural': 'Authentication Users',
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', backends.tenancy.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Only uppercase letters, numbers, underscores', regex='^[A-Z0-9_]+$')])),
                ('abbreviation', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name_vi', models.TextField(max_length=255, verbose_name='Name (Vietnamese)')),
                ('name_en', models.TextField(max_length=255, verbose_name='Name (English)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Study Sites',
                'verbose_name_plural': 'Study Sites',
                'db_table': 'study_sites',
                'ordering': ['id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Only uppercase letters, numbers, underscores', regex='^[A-z0-9_]+$')])),
                ('name_vi', models.TextField(max_length=255, verbose_name='Name (Vietnamese)')),
                ('name_en', models.TextField(max_length=255, verbose_name='Name (English)')),
                ('db_name', models.CharField(blank=True, db_index=True, max_length=100, unique=True, verbose_name='Database Name')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('archived', 'Archived')], db_index=True, default='planning', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studies_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Studies Information',
                'verbose_name_plural': 'Studies Information',
                'db_table': 'study_information',
                'ordering': ['-created_at', 'code'],
            },
        ),
        migrations.CreateModel(
            name='StudySite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_sites_created', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_studies', to='tenancy.site')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sites', to='tenancy.study')),
            ],
            options={
                'verbose_name': 'Study-Site Link',
                'verbose_name_plural': 'Study-Site Links',
                'db_table': 'study_site_links',
            },
        ),
        migrations.CreateModel(
            name='StudyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('can_access_all_sites', models.BooleanField(default=False, help_text='Access to all sites in study')),
                ('notes', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships_assigned', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(help_text='Role group for this study', on_delete=django.db.models.deletion.PROTECT, related_name='study_memberships', to='auth.group', verbose_name='Role (Group)')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenancy.study', verbose_name='Study')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_memberships', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('study_sites', models.ManyToManyField(blank=True, related_name='memberships', to='tenancy.studysite', verbose_name='Study Sites')),
            ],
            options={
                'verbose_name': 'Study Membership',
                'verbose_name_plural': 'Study Memberships',
                'db_table': 'study_memberships',
            },
        ),
        migrations.AddField(
            model_name='study',
            name='sites',
            field=models.ManyToManyField(blank=True, related_name='studies', through='tenancy.StudySite', to='tenancy.site'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='auth_user_usernam_f2740e_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='auth_user_email_ece7f7_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='auth_user_is_acti_9dcf31_idx'),
        ),
        migrations.AddConstraint(
            model_name='studysite',
            constraint=models.UniqueConstraint(fields=('study', 'site'), name='unique_study_site'),
        ),
        migrations.AddIndex(
            model_name='studymembership',
            index=models.Index(fields=['user', 'study', 'is_active'], name='study_membe_user_id_7cf9f6_idx'),
        ),
        migrations.AddIndex(
            model_name='studymembership',
            index=models.Index(fields=['study', 'is_active', 'can_access_all_sites'], name='study_membe_study_i_f99666_idx'),
        ),
        migrations.AddIndex(
            model_name='studymembership',
            index=models.Index(fields=['group', 'is_active'], name='study_membe_group_i_e193d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='studymembership',
            constraint=models.UniqueConstraint(fields=('user', 'study'), name='unique_user_study'),
        ),
    ]
