# Generated by Django 4.2.24 on 2025-12-17 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='key_generated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when RSA key pair was generated', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='key_last_rotated',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last key rotation', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='public_key_pem',
            field=models.TextField(blank=True, help_text="User's RSA public key (PEM format) for backup signature verification", null=True),
        ),
        migrations.CreateModel(
            name='ServerKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key_pem', models.TextField(help_text='RSA private key (encrypted PEM format)')),
                ('public_key_pem', models.TextField(help_text='RSA public key (PEM format)')),
                ('key_size', models.IntegerField(default=4096, help_text='RSA key size in bits')),
                ('fingerprint', models.CharField(help_text='SHA-256 fingerprint of public key', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Is this the active server key pair?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When key was generated')),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this key')),
                ('rotated_from', models.ForeignKey(blank=True, help_text='Previous key (if this is a rotation)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotated_to', to='tenancy.serverkey')),
            ],
            options={
                'verbose_name': 'Server RSA Key',
                'verbose_name_plural': 'Server RSA Keys',
                'db_table': 'tenancy_server_key',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='tenancy_ser_is_acti_0ee0b3_idx'), models.Index(fields=['created_at'], name='tenancy_ser_created_ba5528_idx')],
            },
        ),
        migrations.CreateModel(
            name='EncryptionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ENCRYPT', 'Encrypted'), ('DECRYPT', 'Decrypted'), ('VERIFY', 'Verified'), ('KEY_GEN', 'Key Generated'), ('KEY_ROTATE', 'Key Rotated')], db_index=True, max_length=20)),
                ('backup_file', models.CharField(help_text='Backup file path', max_length=500)),
                ('success', models.BooleanField(default=True, help_text='Operation succeeded?')),
                ('signature_valid', models.BooleanField(blank=True, help_text='Was signature valid? (for decrypt/verify)', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of requester', null=True)),
                ('details', models.JSONField(default=dict, help_text='Additional operation details (error messages, file sizes, etc.)')),
                ('backup_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encryption_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Encryption Audit Log',
                'verbose_name_plural': 'Encryption Audit Logs',
                'db_table': 'tenancy_encryption_audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', '-timestamp'], name='tenancy_enc_action_7ee35c_idx'), models.Index(fields=['user', '-timestamp'], name='tenancy_enc_user_id_17734c_idx'), models.Index(fields=['success', '-timestamp'], name='tenancy_enc_success_02c571_idx')],
            },
        ),
    ]
