# Generated by Django 6.0 on 2026-01-05 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_user_key_generated_at_user_key_last_rotated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={'ordering': ['code'], 'verbose_name': 'Studies Information', 'verbose_name_plural': 'Studies Information'},
        ),
    ]
