# Generated by Django 5.2.10 on 2026-01-15 03:50

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_43en', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_data',
            name='HOUSE_NUMBER',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, help_text='House number, building, apartment details (old system, encrypted)', max_length=255, null=True, verbose_name='House Number/Building Details (Old Administrative Division)'),
        ),
        migrations.AddField(
            model_name='personal_data',
            name='HOUSE_NUMBER_NEW',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, help_text='House number, building, apartment details (new system, encrypted)', max_length=255, null=True, verbose_name='House Number/Building Details (New Administrative Division)'),
        ),
        migrations.AlterField(
            model_name='personal_data',
            name='STREET',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Street name under old administrative structure', max_length=255, null=True, verbose_name='Street/Road Name (Old Administrative Division)'),
        ),
        migrations.AlterField(
            model_name='personal_data',
            name='STREET_NEW',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Street name under new administrative structure', max_length=255, null=True, verbose_name='Street/Road Name (New Administrative Division)'),
        ),
    ]
