# Generated by Django 5.2.10 on 2026-01-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_43en', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enr_contact',
            name='RECRUITDEPT',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Recruitment Department'),
        ),
    ]
