# Generated by Django 4.2.24 on 2025-11-17 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_43en', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fu_case_90',
            name='INITIAL',
        ),
        migrations.RemoveField(
            model_name='fu_case_90',
            name='SITEID',
        ),
        migrations.RemoveField(
            model_name='fu_case_90',
            name='STUDYID',
        ),
        migrations.RemoveField(
            model_name='fu_case_90',
            name='SUBJID',
        ),
        migrations.RemoveField(
            model_name='fu_case_90',
            name='Time_Evaluation',
        ),
        migrations.RemoveField(
            model_name='symptom_72h',
            name='COMPLETEDBY',
        ),
        migrations.RemoveField(
            model_name='symptom_72h',
            name='COMPLETEDDATE',
        ),
    ]
