# Generated by Django 4.2.24 on 2025-11-17 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_43en', '0002_remove_fu_case_90_initial_remove_fu_case_90_siteid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupstatus',
            name='MISSED_DATE',
            field=models.DateField(blank=True, null=True, verbose_name='Missed Date'),
        ),
        migrations.AddField(
            model_name='followupstatus',
            name='MISSED_REASON',
            field=models.TextField(blank=True, null=True, verbose_name='Missed Reason'),
        ),
        migrations.AlterField(
            model_name='dischargeicd',
            name='ICD_SEQUENCE',
            field=models.IntegerField(default=1, help_text='Auto-generated if not provided', validators=[django.core.validators.MinValueValidator(1)], verbose_name='ICD Sequence'),
        ),
    ]
