# Generated by Django 4.2.24 on 2025-11-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_43en', '0003_followupstatus_missed_date_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='improvesympt',
            name='idx_is_improved',
        ),
        migrations.RemoveField(
            model_name='improvesympt',
            name='IMPROVE_SYMPTS',
        ),
        migrations.AlterField(
            model_name='antibioticsensitivity',
            name='TIER',
            field=models.CharField(choices=[('Tier1', ' Tier 1'), ('Tier2', ' Tier 2'), ('Tier3', ' Tier 3'), ('Tier4', ' Tier 4'), ('UrineOnly', ' Urine Only'), ('Colistin', ' Colistin'), ('Other', 'Other')], db_index=True, help_text='WHO AWaRe classification tier', max_length=20, verbose_name='Antibiotic Tier'),
        ),
    ]
