# Generated by Django 4.2.24 on 2025-11-26 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_43en', '0004_remove_improvesympt_idx_is_improved_and_more'),
    ]

    operations = [
        # Some databases may have already dropped this constraint when the
        # referenced field was removed in a prior migration. Use IF EXISTS to
        # avoid failing the migration if the constraint is absent.
        migrations.RunSQL(
            sql=(
                'ALTER TABLE "CLI_Improve_Sympt" '
                'DROP CONSTRAINT IF EXISTS is_specify_if_improved;'
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
