# Generated by Django 4.2.24 on 2025-11-26 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_43en', '0005_remove_improvesympt_is_specify_if_improved'),
    ]

    operations = [
        # Use IF EXISTS to avoid error if constraint was already removed
        migrations.RunSQL(
            sql=(
                'ALTER TABLE "CLI_Improve_Sympt" '
                'DROP CONSTRAINT IF EXISTS is_specify_if_improved;'
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
