# Generated by Django 4.2.24 on 2025-11-26 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_43en', '0006_remove_improvesympt_is_specify_if_improved'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='improvesympt',
            name='is_specify_if_improved',
        ),
    ]
