# Generated by Django 4.2.24 on 2025-11-26 08:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_43en', '0008_hh_case_hh_exposure_hh_foodfrequency_hh_foodsource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HH_Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0, editable=False, help_text='Version number for optimistic locking')),
                ('last_modified_by_id', models.IntegerField(blank=True, db_index=True, editable=False, help_text='User ID who last modified this record', null=True)),
                ('last_modified_by_username', models.CharField(blank=True, db_index=True, editable=False, help_text='Username backup for audit trail', max_length=150, null=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp of last modification')),
                ('ANIMAL_TYPE', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('cow', 'Cow'), ('bird', 'Bird'), ('poultry', 'Chicken/Duck'), ('other', 'Other')], db_index=True, max_length=20)),
                ('ANIMAL_TYPE_OTHER', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animals',
                'db_table': 'HH_Animal',
                'ordering': ['HHID', 'ANIMAL_TYPE'],
            },
        ),
        migrations.CreateModel(
            name='HH_WaterSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0, editable=False, help_text='Version number for optimistic locking')),
                ('last_modified_by_id', models.IntegerField(blank=True, db_index=True, editable=False, help_text='User ID who last modified this record', null=True)),
                ('last_modified_by_username', models.CharField(blank=True, db_index=True, editable=False, help_text='Username backup for audit trail', max_length=150, null=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp of last modification')),
                ('SOURCE_TYPE', models.CharField(choices=[('tap', 'Tap water'), ('bottled', 'Bottled water'), ('well', 'Well water'), ('rain', 'Rain water'), ('river', 'River water'), ('pond', 'Pond/Lake water'), ('other', 'Other')], db_index=True, max_length=20)),
                ('SOURCE_TYPE_OTHER', models.CharField(blank=True, max_length=200, null=True)),
                ('FOR_DRINKING', models.BooleanField(default=False)),
                ('FOR_LIVING', models.BooleanField(default=False)),
                ('FOR_IRRIGATION', models.BooleanField(default=False)),
                ('FOR_OTHER', models.BooleanField(default=False)),
                ('OTHER_PURPOSE', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Water Source',
                'verbose_name_plural': 'Water Sources',
                'db_table': 'HH_WaterSource',
                'ordering': ['HHID', 'SOURCE_TYPE'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='hh_case',
            name='hh_specify_housing_type',
        ),
        migrations.RemoveConstraint(
            model_name='hh_case',
            name='hh_specify_floor_material',
        ),
        migrations.RemoveConstraint(
            model_name='hh_case',
            name='hh_specify_roof_material',
        ),
        migrations.RemoveConstraint(
            model_name='hh_case',
            name='hh_respondent_within_members',
        ),
        migrations.RemoveConstraint(
            model_name='hh_exposure',
            name='exp_specify_toilet_type',
        ),
        migrations.RemoveConstraint(
            model_name='hh_exposure',
            name='exp_specify_cooking_fuel',
        ),
        migrations.RemoveConstraint(
            model_name='hh_exposure',
            name='exp_treatment_method_required',
        ),
        migrations.RemoveConstraint(
            model_name='hh_exposure',
            name='exp_animal_type_required',
        ),
        migrations.RemoveConstraint(
            model_name='hh_exposure',
            name='exp_specify_water_other',
        ),
        migrations.RemoveConstraint(
            model_name='hh_exposure',
            name='exp_specify_treatment_other',
        ),
        migrations.RemoveConstraint(
            model_name='hh_exposure',
            name='exp_specify_animal_other',
        ),
        migrations.RemoveConstraint(
            model_name='hh_foodsource',
            name='src_specify_other',
        ),
        migrations.RemoveConstraint(
            model_name='hh_member',
            name='unique_respondent_per_household',
        ),
        migrations.RemoveConstraint(
            model_name='hh_member',
            name='hhmem_child_must_have_order',
        ),
        migrations.RemoveConstraint(
            model_name='hh_member',
            name='hhmem_non_child_no_order',
        ),
        migrations.RemoveConstraint(
            model_name='hh_member',
            name='unique_child_order_per_household',
        ),
        migrations.RemoveIndex(
            model_name='hh_case',
            name='idx_hh_type',
        ),
        migrations.RemoveIndex(
            model_name='hh_case',
            name='idx_hh_modified',
        ),
        migrations.RemoveIndex(
            model_name='hh_exposure',
            name='idx_exp_water',
        ),
        migrations.RemoveIndex(
            model_name='hh_exposure',
            name='idx_exp_animals',
        ),
        migrations.RemoveIndex(
            model_name='hh_exposure',
            name='idx_exp_modified',
        ),
        migrations.RemoveIndex(
            model_name='hh_foodfrequency',
            name='idx_freq_raw_veg',
        ),
        migrations.RemoveIndex(
            model_name='hh_foodfrequency',
            name='idx_freq_meat',
        ),
        migrations.RemoveIndex(
            model_name='hh_foodfrequency',
            name='idx_freq_modified',
        ),
        migrations.RemoveIndex(
            model_name='hh_foodsource',
            name='idx_src_market',
        ),
        migrations.RemoveIndex(
            model_name='hh_foodsource',
            name='idx_src_super',
        ),
        migrations.RemoveIndex(
            model_name='hh_foodsource',
            name='idx_src_restaurant',
        ),
        migrations.RemoveIndex(
            model_name='hh_foodsource',
            name='idx_src_modified',
        ),
        migrations.RemoveIndex(
            model_name='hh_member',
            name='idx_hhmem_rel',
        ),
        migrations.RemoveIndex(
            model_name='hh_member',
            name='idx_hhmem_demo',
        ),
        migrations.RemoveIndex(
            model_name='hh_member',
            name='idx_hhmem_resp',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='ANIMAL_BIRD',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='ANIMAL_CAT',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='ANIMAL_COW',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='ANIMAL_DOG',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='ANIMAL_OTHER',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='ANIMAL_OTHER_SPECIFY',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='ANIMAL_POULTRY',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='WATER_BOTTLED',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='WATER_BOTTLED_DRINKING',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='WATER_BOTTLED_IRRIGATION',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='WATER_BOTTLED_LIVING',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='WATER_BOTTLED_OTHER',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='WATER_OTHER',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='WATER_OTHER_DRINKING',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='WATER_OTHER_IRRIGATION',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='WATER_OTHER_LIVING',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='WATER_OTHER_PURPOSE',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='WATER_OTHER_SPECIFY',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='WATER_POND',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='WATER_POND_DRINKING',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='WATER_POND_IRRIGATION',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='WATER_POND_LIVING',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='WATER_POND_OTHER',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='WATER_RAIN',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='WATER_RAIN_DRINKING',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='WATER_RAIN_IRRIGATION',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='WATER_RAIN_LIVING',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='WATER_RAIN_OTHER',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='WATER_RIVER',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='WATER_RIVER_DRINKING',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='WATER_RIVER_IRRIGATION',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='WATER_RIVER_LIVING',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='WATER_RIVER_OTHER',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='WATER_TAP',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='WATER_TAP_DRINKING',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='WATER_TAP_IRRIGATION',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='WATER_TAP_LIVING',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='WATER_TAP_OTHER',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='WATER_WELL',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='WATER_WELL_DRINKING',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='WATER_WELL_IRRIGATION',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='WATER_WELL_LIVING',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='WATER_WELL_OTHER',
        ),
        migrations.AlterField(
            model_name='hh_case',
            name='FLOOR_MATERIAL_OTHER',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Other Floor Material'),
        ),
        migrations.AlterField(
            model_name='hh_case',
            name='HHID',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Household ID'),
        ),
        migrations.AlterField(
            model_name='hh_case',
            name='HOUSING_TYPE',
            field=models.CharField(blank=True, choices=[('permanent', 'Permanent house'), ('temporary', 'Temporary/rudimentary house'), ('other', 'Other')], max_length=20, null=True, verbose_name='Housing Type'),
        ),
        migrations.AlterField(
            model_name='hh_case',
            name='HOUSING_TYPE_OTHER',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Other Housing Type'),
        ),
        migrations.AlterField(
            model_name='hh_case',
            name='NUM_FLOORS',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of Floors'),
        ),
        migrations.AlterField(
            model_name='hh_case',
            name='NUM_ROOMS',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of Rooms'),
        ),
        migrations.AlterField(
            model_name='hh_case',
            name='RESPONDENT_MEMBER_NUM',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Respondent Member Number'),
        ),
        migrations.AlterField(
            model_name='hh_case',
            name='ROOF_MATERIAL_OTHER',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Other Roof Material'),
        ),
        migrations.AlterField(
            model_name='hh_exposure',
            name='COOKING_FUEL',
            field=models.CharField(blank=True, choices=[('gas', 'Gas'), ('coal', 'Coal'), ('wood', 'Wood/Firewood'), ('oil', 'Oil'), ('electricity', 'Electricity'), ('other', 'Other')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hh_exposure',
            name='COOKING_FUEL_OTHER',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hh_exposure',
            name='HHID',
            field=models.OneToOneField(db_column='HHID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='exposure', serialize=False, to='study_43en.hh_case'),
        ),
        migrations.AlterField(
            model_name='hh_exposure',
            name='NUM_TOILETS',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='hh_exposure',
            name='RAISES_ANIMALS',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hh_exposure',
            name='TOILET_TYPE',
            field=models.CharField(blank=True, choices=[('septic_flush', 'Toilet with septic tank'), ('no_septic', 'Toilet without septic tank'), ('outdoor', 'Outdoor toilet'), ('no_toilet', 'No toilet'), ('other', 'Other')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hh_exposure',
            name='TOILET_TYPE_OTHER',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hh_exposure',
            name='TREATMENT_BOILING',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hh_exposure',
            name='TREATMENT_CHEMICAL',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hh_exposure',
            name='TREATMENT_FILTER_MACHINE',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hh_exposure',
            name='TREATMENT_FILTER_PORTABLE',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hh_exposure',
            name='TREATMENT_OTHER',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hh_exposure',
            name='TREATMENT_OTHER_SPECIFY',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hh_exposure',
            name='TREATMENT_SODIS',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hh_exposure',
            name='WATER_TREATMENT',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hh_foodfrequency',
            name='FREQ_ALCOHOL',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('1-3/month', '1-3 times/month'), ('1-2/week', '1-2 times/week'), ('3-5/week', '3-5 times/week'), ('1/day', '1 time/day'), ('2+/day', '2+ times/day')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='hh_foodfrequency',
            name='FREQ_BEER',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('1-3/month', '1-3 times/month'), ('1-2/week', '1-2 times/week'), ('3-5/week', '3-5 times/week'), ('1/day', '1 time/day'), ('2+/day', '2+ times/day')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='hh_foodfrequency',
            name='FREQ_COOKED_VEGETABLES',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('1-3/month', '1-3 times/month'), ('1-2/week', '1-2 times/week'), ('3-5/week', '3-5 times/week'), ('1/day', '1 time/day'), ('2+/day', '2+ times/day')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='hh_foodfrequency',
            name='FREQ_DAIRY',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('1-3/month', '1-3 times/month'), ('1-2/week', '1-2 times/week'), ('3-5/week', '3-5 times/week'), ('1/day', '1 time/day'), ('2+/day', '2+ times/day')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='hh_foodfrequency',
            name='FREQ_EGGS',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('1-3/month', '1-3 times/month'), ('1-2/week', '1-2 times/week'), ('3-5/week', '3-5 times/week'), ('1/day', '1 time/day'), ('2+/day', '2+ times/day')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='hh_foodfrequency',
            name='FREQ_FERMENTED',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('1-3/month', '1-3 times/month'), ('1-2/week', '1-2 times/week'), ('3-5/week', '3-5 times/week'), ('1/day', '1 time/day'), ('2+/day', '2+ times/day')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='hh_foodfrequency',
            name='FREQ_FISH_SEAFOOD',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('1-3/month', '1-3 times/month'), ('1-2/week', '1-2 times/week'), ('3-5/week', '3-5 times/week'), ('1/day', '1 time/day'), ('2+/day', '2+ times/day')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='hh_foodfrequency',
            name='FREQ_POULTRY',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('1-3/month', '1-3 times/month'), ('1-2/week', '1-2 times/week'), ('3-5/week', '3-5 times/week'), ('1/day', '1 time/day'), ('2+/day', '2+ times/day')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='hh_foodfrequency',
            name='FREQ_RAW_VEGETABLES',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('1-3/month', '1-3 times/month'), ('1-2/week', '1-2 times/week'), ('3-5/week', '3-5 times/week'), ('1/day', '1 time/day'), ('2+/day', '2+ times/day')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='hh_foodfrequency',
            name='FREQ_RED_MEAT',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('1-3/month', '1-3 times/month'), ('1-2/week', '1-2 times/week'), ('3-5/week', '3-5 times/week'), ('1/day', '1 time/day'), ('2+/day', '2+ times/day')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='hh_foodfrequency',
            name='FREQ_RICE_NOODLES',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('1-3/month', '1-3 times/month'), ('1-2/week', '1-2 times/week'), ('3-5/week', '3-5 times/week'), ('1/day', '1 time/day'), ('2+/day', '2+ times/day')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='hh_foodfrequency',
            name='HHID',
            field=models.OneToOneField(db_column='HHID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='food_frequency', serialize=False, to='study_43en.hh_case'),
        ),
        migrations.AlterField(
            model_name='hh_foodsource',
            name='HHID',
            field=models.OneToOneField(db_column='HHID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='food_source', serialize=False, to='study_43en.hh_case'),
        ),
        migrations.AlterField(
            model_name='hh_foodsource',
            name='SOURCE_CONVENIENCE_STORE',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('1-3/month', '1-3 times/month'), ('1-2/week', '1-2 times/week'), ('3-5/week', '3-5 times/week'), ('1/day', '1 time/day'), ('2+/day', '2+ times/day')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='hh_foodsource',
            name='SOURCE_GIFTED',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('1-3/month', '1-3 times/month'), ('1-2/week', '1-2 times/week'), ('3-5/week', '3-5 times/week'), ('1/day', '1 time/day'), ('2+/day', '2+ times/day')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='hh_foodsource',
            name='SOURCE_ONLINE',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('1-3/month', '1-3 times/month'), ('1-2/week', '1-2 times/week'), ('3-5/week', '3-5 times/week'), ('1/day', '1 time/day'), ('2+/day', '2+ times/day')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='hh_foodsource',
            name='SOURCE_OTHER',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('1-3/month', '1-3 times/month'), ('1-2/week', '1-2 times/week'), ('3-5/week', '3-5 times/week'), ('1/day', '1 time/day'), ('2+/day', '2+ times/day')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='hh_foodsource',
            name='SOURCE_OTHER_SPECIFY',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hh_foodsource',
            name='SOURCE_RESTAURANT',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('1-3/month', '1-3 times/month'), ('1-2/week', '1-2 times/week'), ('3-5/week', '3-5 times/week'), ('1/day', '1 time/day'), ('2+/day', '2+ times/day')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='hh_foodsource',
            name='SOURCE_SELF_GROWN',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('1-3/month', '1-3 times/month'), ('1-2/week', '1-2 times/week'), ('3-5/week', '3-5 times/week'), ('1/day', '1 time/day'), ('2+/day', '2+ times/day')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='hh_foodsource',
            name='SOURCE_SUPERMARKET',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('1-3/month', '1-3 times/month'), ('1-2/week', '1-2 times/week'), ('3-5/week', '3-5 times/week'), ('1/day', '1 time/day'), ('2+/day', '2+ times/day')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='hh_foodsource',
            name='SOURCE_TRADITIONAL_MARKET',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('1-3/month', '1-3 times/month'), ('1-2/week', '1-2 times/week'), ('3-5/week', '3-5 times/week'), ('1/day', '1 time/day'), ('2+/day', '2+ times/day')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='hh_member',
            name='BIRTH_YEAR',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900)], verbose_name='Birth Year'),
        ),
        migrations.AlterField(
            model_name='hh_member',
            name='CHILD_ORDER',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Child Order'),
        ),
        migrations.AlterField(
            model_name='hh_member',
            name='HHID',
            field=models.ForeignKey(db_column='HHID', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='study_43en.hh_case'),
        ),
        migrations.AlterField(
            model_name='hh_member',
            name='ISRESPONDENT',
            field=models.BooleanField(default=False, verbose_name='Is Respondent'),
        ),
        migrations.AlterField(
            model_name='hh_member',
            name='MEMBER_NUM',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Member Number'),
        ),
        migrations.AlterField(
            model_name='hh_member',
            name='RELATIONSHIP',
            field=models.CharField(blank=True, choices=[('A', 'Household head'), ('B', 'Wife'), ('C', 'Husband'), ('D', 'Child'), ('E', 'Parent'), ('F', 'Grandparent'), ('G', 'Other')], max_length=5, null=True, verbose_name='Relationship'),
        ),
        migrations.AddConstraint(
            model_name='hh_member',
            constraint=models.UniqueConstraint(condition=models.Q(('ISRESPONDENT', True)), fields=('HHID',), name='unique_respondent'),
        ),
        migrations.AddConstraint(
            model_name='hh_member',
            constraint=models.UniqueConstraint(condition=models.Q(('RELATIONSHIP', 'D')), fields=('HHID', 'CHILD_ORDER'), name='unique_child_order'),
        ),
        migrations.AddField(
            model_name='hh_watersource',
            name='HHID',
            field=models.ForeignKey(db_column='HHID', on_delete=django.db.models.deletion.CASCADE, related_name='water_sources', to='study_43en.hh_exposure'),
        ),
        migrations.AddField(
            model_name='hh_animal',
            name='HHID',
            field=models.ForeignKey(db_column='HHID', on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='study_43en.hh_exposure'),
        ),
        migrations.AddIndex(
            model_name='hh_watersource',
            index=models.Index(fields=['HHID', 'SOURCE_TYPE'], name='idx_water_hh_type'),
        ),
        migrations.AddIndex(
            model_name='hh_watersource',
            index=models.Index(fields=['FOR_DRINKING'], name='idx_water_drinking'),
        ),
        migrations.AlterUniqueTogether(
            name='hh_watersource',
            unique_together={('HHID', 'SOURCE_TYPE')},
        ),
        migrations.AddIndex(
            model_name='hh_animal',
            index=models.Index(fields=['HHID', 'ANIMAL_TYPE'], name='idx_animal_hh_type'),
        ),
        migrations.AlterUniqueTogether(
            name='hh_animal',
            unique_together={('HHID', 'ANIMAL_TYPE')},
        ),
    ]
