# Generated by Django 4.2.24 on 2025-11-26 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_43en', '0009_hh_animal_hh_watersource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HH_WaterTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0, editable=False, help_text='Version number for optimistic locking')),
                ('last_modified_by_id', models.IntegerField(blank=True, db_index=True, editable=False, help_text='User ID who last modified this record', null=True)),
                ('last_modified_by_username', models.CharField(blank=True, db_index=True, editable=False, help_text='Username backup for audit trail', max_length=150, null=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp of last modification')),
                ('TREATMENT_TYPE', models.CharField(choices=[('boiling', 'Boiling'), ('filter_machine', 'Filter machine'), ('filter_portable', 'Portable filter'), ('chemical', 'Chemical disinfection'), ('sodis', 'Solar disinfection (SODIS)'), ('other', 'Other')], db_index=True, max_length=20)),
                ('TREATMENT_TYPE_OTHER', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Water Treatment Method',
                'verbose_name_plural': 'Water Treatment Methods',
                'db_table': 'HH_WaterTreatment',
                'ordering': ['HHID', 'TREATMENT_TYPE'],
            },
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='TREATMENT_BOILING',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='TREATMENT_CHEMICAL',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='TREATMENT_FILTER_MACHINE',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='TREATMENT_FILTER_PORTABLE',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='TREATMENT_OTHER',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='TREATMENT_OTHER_SPECIFY',
        ),
        migrations.RemoveField(
            model_name='hh_exposure',
            name='TREATMENT_SODIS',
        ),
        migrations.AddIndex(
            model_name='hh_exposure',
            index=models.Index(fields=['WATER_TREATMENT'], name='idx_exp_water'),
        ),
        migrations.AddIndex(
            model_name='hh_exposure',
            index=models.Index(fields=['RAISES_ANIMALS'], name='idx_exp_animals'),
        ),
        migrations.AddField(
            model_name='hh_watertreatment',
            name='HHID',
            field=models.ForeignKey(db_column='HHID', on_delete=django.db.models.deletion.CASCADE, related_name='treatment_methods', to='study_43en.hh_exposure'),
        ),
        migrations.AddIndex(
            model_name='hh_watertreatment',
            index=models.Index(fields=['HHID', 'TREATMENT_TYPE'], name='idx_treatment_hh_type'),
        ),
        migrations.AlterUniqueTogether(
            name='hh_watertreatment',
            unique_together={('HHID', 'TREATMENT_TYPE')},
        ),
    ]
