# Generated by Django 4.2.24 on 2025-11-26 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_43en', '0010_hh_watertreatment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hh_foodfrequency',
            old_name='FREQ_ALCOHOL',
            new_name='ALCOHOL',
        ),
        migrations.RenameField(
            model_name='hh_foodfrequency',
            old_name='FREQ_BEER',
            new_name='BEER',
        ),
        migrations.RenameField(
            model_name='hh_foodfrequency',
            old_name='FREQ_COOKED_VEGETABLES',
            new_name='COOKED_VEGETABLES',
        ),
        migrations.RenameField(
            model_name='hh_foodfrequency',
            old_name='FREQ_DAIRY',
            new_name='DAIRY',
        ),
        migrations.RenameField(
            model_name='hh_foodfrequency',
            old_name='FREQ_EGGS',
            new_name='EGGS',
        ),
        migrations.RenameField(
            model_name='hh_foodfrequency',
            old_name='FREQ_FERMENTED',
            new_name='FERMENTED',
        ),
        migrations.RenameField(
            model_name='hh_foodfrequency',
            old_name='FREQ_FISH_SEAFOOD',
            new_name='FISH_SEAFOOD',
        ),
        migrations.RenameField(
            model_name='hh_foodfrequency',
            old_name='FREQ_POULTRY',
            new_name='POULTRY',
        ),
        migrations.RenameField(
            model_name='hh_foodfrequency',
            old_name='FREQ_RAW_VEGETABLES',
            new_name='RAW_VEGETABLES',
        ),
        migrations.RenameField(
            model_name='hh_foodfrequency',
            old_name='FREQ_RED_MEAT',
            new_name='RED_MEAT',
        ),
        migrations.RenameField(
            model_name='hh_foodfrequency',
            old_name='FREQ_RICE_NOODLES',
            new_name='RICE_NOODLES',
        ),
    ]
