# Generated by Django 4.2.24 on 2025-11-26 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_43en', '0011_rename_freq_alcohol_hh_foodfrequency_alcohol_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hh_foodsource',
            old_name='SOURCE_CONVENIENCE_STORE',
            new_name='CONVENIENCE_STORE',
        ),
        migrations.RenameField(
            model_name='hh_foodsource',
            old_name='SOURCE_GIFTED',
            new_name='GIFTED',
        ),
        migrations.RenameField(
            model_name='hh_foodsource',
            old_name='SOURCE_ONLINE',
            new_name='ONLINE',
        ),
        migrations.RenameField(
            model_name='hh_foodsource',
            old_name='SOURCE_OTHER',
            new_name='OTHER',
        ),
        migrations.RenameField(
            model_name='hh_foodsource',
            old_name='SOURCE_OTHER_SPECIFY',
            new_name='OTHER_SPECIFY',
        ),
        migrations.RenameField(
            model_name='hh_foodsource',
            old_name='SOURCE_RESTAURANT',
            new_name='RESTAURANT',
        ),
        migrations.RenameField(
            model_name='hh_foodsource',
            old_name='SOURCE_SELF_GROWN',
            new_name='SELF_GROWN',
        ),
        migrations.RenameField(
            model_name='hh_foodsource',
            old_name='SOURCE_SUPERMARKET',
            new_name='SUPERMARKET',
        ),
        migrations.RenameField(
            model_name='hh_foodsource',
            old_name='SOURCE_TRADITIONAL_MARKET',
            new_name='TRADITIONAL_MARKET',
        ),
    ]
