# Generated by Django 4.2.24 on 2025-12-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_43en', '0013_individual_individual_followup_individual_exposure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorytest',
            name='data_entered',
            field=models.BooleanField(db_index=True, default=False, help_text='True if test data has been entered at least once', verbose_name='Data Entered'),
        ),
        migrations.AlterField(
            model_name='individual_exposure',
            name='MEDICATION_3M',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=20, null=True, verbose_name='Used Medication (3 months)'),
        ),
        migrations.AddIndex(
            model_name='laboratorytest',
            index=models.Index(fields=['USUBJID', 'data_entered', 'LAB_TYPE'], name='idx_lab_data_entered'),
        ),
        migrations.AddIndex(
            model_name='laboratorytest',
            index=models.Index(fields=['data_entered', 'PERFORMED'], name='idx_lab_entry_status'),
        ),
    ]
