# Generated by Django 4.2.24 on 2025-12-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_43en', '0014_laboratorytest_data_entered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cli_case',
            name='NEWS2',
            field=models.CharField(blank=True, choices=[('low', '0-4 Low'), ('medium', '5-6 Medium'), ('high', '≥7 High')], max_length=10, null=True, verbose_name='NEWS2 Score (0-20)'),
        ),
    ]
