# Generated by Django 4.2.24 on 2025-12-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_43en', '0015_alter_cli_case_news2'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='hh_watersource',
            name='idx_water_drinking',
        ),
        migrations.RenameField(
            model_name='hh_case',
            old_name='HAS_AC',
            new_name='AC',
        ),
        migrations.RenameField(
            model_name='hh_case',
            old_name='HAS_BICYCLE',
            new_name='BICYCLE',
        ),
        migrations.RenameField(
            model_name='hh_case',
            old_name='HAS_CAR',
            new_name='CAR',
        ),
        migrations.RenameField(
            model_name='hh_case',
            old_name='HAS_COMPUTER',
            new_name='COMPUTER',
        ),
        migrations.RenameField(
            model_name='hh_case',
            old_name='HAS_GAS_STOVE',
            new_name='GAS_STOVE',
        ),
        migrations.RenameField(
            model_name='hh_case',
            old_name='HAS_INDUCTION_COOKER',
            new_name='INDUCTION_COOKER',
        ),
        migrations.RenameField(
            model_name='hh_case',
            old_name='HAS_INTERNET',
            new_name='INTERNET',
        ),
        migrations.RenameField(
            model_name='hh_case',
            old_name='HAS_MOBILE_PHONE',
            new_name='MOBILE_PHONE',
        ),
        migrations.RenameField(
            model_name='hh_case',
            old_name='HAS_MOTORCYCLE',
            new_name='MOTORCYCLE',
        ),
        migrations.RenameField(
            model_name='hh_case',
            old_name='HAS_REFRIGERATOR',
            new_name='REFRIGERATOR',
        ),
        migrations.RenameField(
            model_name='hh_case',
            old_name='HAS_RICE_COOKER',
            new_name='RICE_COOKER',
        ),
        migrations.RenameField(
            model_name='hh_case',
            old_name='HAS_TV',
            new_name='TV',
        ),
        migrations.RenameField(
            model_name='hh_case',
            old_name='HAS_WASHING_MACHINE',
            new_name='WASHING_MACHINE',
        ),
        migrations.RenameField(
            model_name='hh_case',
            old_name='HAS_WATER_HEATER',
            new_name='WATER_HEATER',
        ),
        migrations.RenameField(
            model_name='hh_watersource',
            old_name='FOR_DRINKING',
            new_name='DRINKING',
        ),
        migrations.RenameField(
            model_name='hh_watersource',
            old_name='FOR_IRRIGATION',
            new_name='IRRIGATION',
        ),
        migrations.RenameField(
            model_name='hh_watersource',
            old_name='FOR_LIVING',
            new_name='LIVING',
        ),
        migrations.RenameField(
            model_name='hh_watersource',
            old_name='FOR_OTHER',
            new_name='OTHER',
        ),
        migrations.RenameField(
            model_name='individual_watersource',
            old_name='FOR_DRINKING',
            new_name='DRINKING',
        ),
        migrations.RenameField(
            model_name='individual_watersource',
            old_name='FOR_IRRIGATION',
            new_name='IRRIGATION',
        ),
        migrations.RenameField(
            model_name='individual_watersource',
            old_name='FOR_LIVING',
            new_name='LIVING',
        ),
        migrations.AddIndex(
            model_name='hh_watersource',
            index=models.Index(fields=['DRINKING'], name='idx_water_drinking'),
        ),
    ]
