# Generated by Django 6.0 on 2026-01-05 03:37

import django.db.models.deletion
import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_43en', '0017_remove_hh_exposure_hhid_remove_hh_foodfrequency_hhid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PERSONAL_CONTACT_DATA',
            fields=[
                ('version', models.IntegerField(default=0, editable=False, help_text='Version number for optimistic locking')),
                ('last_modified_by_id', models.IntegerField(blank=True, db_index=True, editable=False, help_text='User ID who last modified this record', null=True)),
                ('last_modified_by_username', models.CharField(blank=True, db_index=True, editable=False, help_text='Username backup for audit trail', max_length=150, null=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp of last modification')),
                ('USUBJID', models.OneToOneField(db_column='USUBJID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='personal_data', serialize=False, to='study_43en.enr_contact', verbose_name='Contact ID')),
                ('FULLNAME', encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Contact full name (encrypted)', null=True, verbose_name='Full Name')),
                ('PHONE', encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Contact phone number (encrypted)', null=True, verbose_name='Phone Number')),
            ],
            options={
                'verbose_name': 'Contact Personal Data',
                'verbose_name_plural': 'Contact Personal Data',
                'db_table': 'PERSONAL_CONTACT_DATA',
            },
        ),
        migrations.CreateModel(
            name='PERSONAL_DATA',
            fields=[
                ('version', models.IntegerField(default=0, editable=False, help_text='Version number for optimistic locking')),
                ('last_modified_by_id', models.IntegerField(blank=True, db_index=True, editable=False, help_text='User ID who last modified this record', null=True)),
                ('last_modified_by_username', models.CharField(blank=True, db_index=True, editable=False, help_text='Username backup for audit trail', max_length=150, null=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp of last modification')),
                ('USUBJID', models.OneToOneField(db_column='USUBJID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='personal_data', serialize=False, to='study_43en.enr_case', verbose_name='Patient ID')),
                ('FULLNAME', encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Patient full name (encrypted)', null=True, verbose_name='Full Name')),
                ('PHONE', encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Contact phone number (encrypted)', null=True, verbose_name='Phone Number')),
                ('MEDRECORDID', encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Hospital medical record ID (encrypted)', null=True, verbose_name='Medical Record Number')),
                ('STREET_NEW', encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Street name under new administrative structure', null=True, verbose_name='Street/Road (New Administrative Division)')),
                ('WARD_NEW', encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Ward/commune under new administrative structure', null=True, verbose_name='Ward/Commune (New Administrative Division)')),
                ('CITY_NEW', encrypted_fields.fields.EncryptedCharField(blank=True, help_text='City/province under new administrative structure', null=True, verbose_name='City/Province (New Administrative Division)')),
                ('STREET', encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Street name under old administrative structure', null=True, verbose_name='Street/Road (Old Administrative Division)')),
                ('WARD', encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Ward/commune under old administrative structure', null=True, verbose_name='Ward/Commune (Old Administrative Division)')),
                ('DISTRICT', encrypted_fields.fields.EncryptedCharField(blank=True, help_text='District under old administrative structure', null=True, verbose_name='District/County (Old Administrative Division)')),
                ('PROVINCECITY', encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Province/city under old administrative structure', null=True, verbose_name='Province/City (Old Administrative Division)')),
                ('PRIMARY_ADDRESS', models.CharField(choices=[('new', 'New Address'), ('old', 'Old Address'), ('both', 'Both Addresses')], default='new', help_text='Which address system to use as primary', max_length=10, verbose_name='Primary Address System')),
            ],
            options={
                'verbose_name': 'Patient Personal Data',
                'verbose_name_plural': 'Patient Personal Data',
                'db_table': 'PERSONAL_DATA',
            },
        ),
        migrations.RemoveConstraint(
            model_name='enr_case',
            name='enr_valid_date_components',
        ),
        migrations.RemoveConstraint(
            model_name='enr_case',
            name='enr_prior_date_if_transferred',
        ),
        migrations.RemoveIndex(
            model_name='enr_case',
            name='idx_enr_location',
        ),
        migrations.RemoveField(
            model_name='enr_contact',
            name='FULLNAME',
        ),
        migrations.RemoveField(
            model_name='enr_contact',
            name='PHONE',
        ),
        migrations.AddIndex(
            model_name='personal_contact_data',
            index=models.Index(fields=['last_modified_by_id', '-last_modified_at'], name='idx_pcdata_modified'),
        ),
        migrations.AddIndex(
            model_name='personal_data',
            index=models.Index(fields=['last_modified_by_id', '-last_modified_at'], name='idx_pdata_modified'),
        ),
        migrations.RemoveField(
            model_name='enr_case',
            name='CITY_NEW',
        ),
        migrations.RemoveField(
            model_name='enr_case',
            name='DISTRICT',
        ),
        migrations.RemoveField(
            model_name='enr_case',
            name='FULLNAME',
        ),
        migrations.RemoveField(
            model_name='enr_case',
            name='MEDRECORDID',
        ),
        migrations.RemoveField(
            model_name='enr_case',
            name='PHONE',
        ),
        migrations.RemoveField(
            model_name='enr_case',
            name='PRIMARY_ADDRESS',
        ),
        migrations.RemoveField(
            model_name='enr_case',
            name='PROVINCECITY',
        ),
        migrations.RemoveField(
            model_name='enr_case',
            name='STREET',
        ),
        migrations.RemoveField(
            model_name='enr_case',
            name='STREET_NEW',
        ),
        migrations.RemoveField(
            model_name='enr_case',
            name='WARD',
        ),
        migrations.RemoveField(
            model_name='enr_case',
            name='WARD_NEW',
        ),
    ]
