# Generated by Django 6.0 on 2026-01-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_43en', '0018_personal_contact_data_personal_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_data',
            name='PRIMARY_ADDRESS',
            field=models.CharField(blank=True, choices=[('new', 'New Address'), ('old', 'Old Address'), ('both', 'Both Addresses')], help_text='Which address system to use as primary', max_length=10, null=True, verbose_name='Primary Address System'),
        ),
    ]
