# Generated by Django 6.0 on 2026-01-05 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_43en', '0019_alter_personal_data_primary_address'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_log_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_log_patient_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_log_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_log_site_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_log_model_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlogdetail',
            name='audit_detail_log_idx',
        ),
        migrations.RemoveField(
            model_name='auditlogdetail',
            name='audit_log',
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='AuditLogDetail',
        ),
    ]
