# Generated by Django 6.0 on 2026-01-08 08:43

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_43en', '0020_remove_auditlog_audit_log_time_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupstatus',
            name='PHONE',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='personal_contact_data',
            name='FULLNAME',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Contact full name (encrypted)', max_length=255, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='personal_contact_data',
            name='PHONE',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Contact phone number (encrypted)', max_length=255, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='personal_data',
            name='CITY_NEW',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, help_text='City/province under new administrative structure', max_length=255, null=True, verbose_name='City/Province (New Administrative Division)'),
        ),
        migrations.AlterField(
            model_name='personal_data',
            name='DISTRICT',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, help_text='District under old administrative structure', max_length=255, null=True, verbose_name='District/County (Old Administrative Division)'),
        ),
        migrations.AlterField(
            model_name='personal_data',
            name='FULLNAME',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Patient full name (encrypted)', max_length=255, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='personal_data',
            name='MEDRECORDID',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Hospital medical record ID (encrypted)', max_length=255, null=True, verbose_name='Medical Record Number'),
        ),
        migrations.AlterField(
            model_name='personal_data',
            name='PHONE',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Contact phone number (encrypted)', max_length=255, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='personal_data',
            name='PROVINCECITY',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Province/city under old administrative structure', max_length=255, null=True, verbose_name='Province/City (Old Administrative Division)'),
        ),
        migrations.AlterField(
            model_name='personal_data',
            name='STREET',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Street name under old administrative structure', max_length=255, null=True, verbose_name='Street/Road (Old Administrative Division)'),
        ),
        migrations.AlterField(
            model_name='personal_data',
            name='STREET_NEW',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Street name under new administrative structure', max_length=255, null=True, verbose_name='Street/Road (New Administrative Division)'),
        ),
        migrations.AlterField(
            model_name='personal_data',
            name='WARD',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Ward/commune under old administrative structure', max_length=255, null=True, verbose_name='Ward/Commune (Old Administrative Division)'),
        ),
        migrations.AlterField(
            model_name='personal_data',
            name='WARD_NEW',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Ward/commune under new administrative structure', max_length=255, null=True, verbose_name='Ward/Commune (New Administrative Division)'),
        ),
    ]
